server:
  port: 8100

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaximoDiNapoli/Facturacion-Caso-Estudio.git
          password: ${GIT_PASSWORD}
          username: ${GIT_USER}
          search-paths: config-data
        enabled: true
  security:
    user:
      name: root
      password: s3cr3t
  application:
    name: config-server


